services:
  - type: web
    name: ml-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    runtime: python3.11
    envVars:
      - key: DB_HOST
        value: yamanote.proxy.rlwy.net
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: EoJhzIWGIkfIyHVOEnPBrGTMYKMpGyLB
      - key: DB_NAME
        value: railway
      - key: DB_PORT
        value: 55190